server:
  port: 8084

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 3000m
  db:
    database: hm-user
  swagger:
    title: "黑马商城用户服务接口文档"
    package: com.hmall.user.controller